version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ec2-user/app/step3/zip/
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user # codedeploy에서 ec2 서버로 넘겨준 파일들을 모두 ec2-user 권한을 갖도록 한다
    group: ec2-user

# hooks : CodeDeploy 배포단계에서 실행할 명령어
hooks: # ApplicationStart 단계에서 deploy.sh 를 ec2-user 권한으로 실행하게된다.
  AfterInstall:
    - location: stop.sh # 엔진엑스와 연결되어 있지 않지만, 실행중이던 스프링부트 종료
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: start  .sh #엔진엑스와 연결되어있지않은 port로 새버전의 스프링부트 시작
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: health.sh # 새 스프링부트가 정상적으로 실행됐는지 확인
      timeout: 60
      runas: ec2-user